title: Cogear.JS – modern static websites generator
description: Modern static websites generator built with Node.JS and based on Webpack.
url: https://cogearjs.org
keywords: 
theme: false
deploy:
  production:
    type: rsync
    host: 37.143.8.212 
    user: cogear
    commands: "-avz --delete --progress --quiet"
    path: /home/cogear/www/cogearjs.org/
blog:
  tagUri: 'blog/tag/'
pages:
  ^docs/:
    layout: docs
    js:
      - js/docs.js
  ^blog:
    layout: blog
    js:
      - js/blog.js
    author: 
      name: Dmitry Beliaev
      github: https://github.com/codemotion
feed:
  image_url: https://cogearjs.org/images/cogearjs.jpg